In [2]:
import numpy as np

 `np.array()`: This function is used to create an array in NumPy.

**Example**

In [3]:
arr = np.array([1,2,4,5,6])

print(arr)

[1 2 4 5 6]


In [4]:
rarr = np.arange(1, 6)

print(rarr)

[1 2 3 4 5]


In [8]:
arr = np.zeros(3)

print(arr)

[0. 0. 0.]


In [9]:
arr = np.ones(5)

print(arr)

[1. 1. 1. 1. 1.]


In [10]:
arr = np.linspace(0,1,5)
print(arr)

[0.   0.25 0.5  0.75 1.  ]
