In [40]:
import numpy as np

 `np.array()`: This function is used to create an array in NumPy.

**Example**

In [41]:
arr = np.array([1,2,4,5,6])

print(arr)

[1 2 4 5 6]


In [42]:
rarr = np.arange(1, 6)

print(rarr)

[1 2 3 4 5]


In [43]:
arr = np.zeros(3)

print(arr)

[0. 0. 0.]


In [44]:
arr = np.ones(5)

print(arr)

[1. 1. 1. 1. 1.]


In [45]:
arr = np.linspace(0,1,5)
print(arr)

[0.   0.25 0.5  0.75 1.  ]


In [46]:
arr = np.random.rand(5)

print(arr)

[0.0724612  0.56902272 0.55407595 0.49018851 0.22756877]


In [47]:
arr = np.random.randint(0,5,10)
print(arr)

[4 4 1 3 4 4 2 1 2 2]


In [48]:
arr = np.random.randint(15,size=(4,3))

print(arr)

arr.reshape(-1)

[[ 1  7 10]
 [12 12  0]
 [ 2  4 12]
 [ 3 11  8]]


array([ 1,  7, 10, 12, 12,  0,  2,  4, 12,  3, 11,  8])