In [2]:
import numpy as np

 `np.array()`: This function is used to create an array in NumPy.

**Example**

In [3]:
arr = np.array([1,2,4,5,6])

print(arr)

[1 2 4 5 6]


In [4]:
rarr = np.arange(1, 6)

print(rarr)

[1 2 3 4 5]


In [8]:
arr = np.zeros(3)

print(arr)

[0. 0. 0.]


In [9]:
arr = np.ones(5)

print(arr)

[1. 1. 1. 1. 1.]


In [10]:
arr = np.linspace(0,1,5)
print(arr)

[0.   0.25 0.5  0.75 1.  ]


In [12]:
arr = np.random.rand(5)

print(arr)

[0.46239645 0.83328575 0.68210161 0.08973749 0.4169188 ]


In [16]:
arr = np.random.randint(0,5,10)
print(arr)

[2 0 1 3 4 3 4 2 1 0]
